apiVersion: v1
kind: Service
metadata:
  name: ranking-service
spec:
  selector:
    app: ranking-service
  ports:
    - protocol: TCP
      port: 8081  # Porta acessível externamente
      targetPort: 8081  # Porta dentro do container
      nodePort: 30081
  type: LoadBalancer  # Para expor externamente, pode ser NodePort ou ClusterIP, dependendo do ambiente
