apiVersion: v1
kind: Service
metadata:
  name: score-service
spec:
  selector:
    app: score-service
  ports:
    - protocol: TCP
      port: 8080  # Porta acessível externamente
      targetPort: 8080  # Porta dentro do container
      nodePort: 30080
  type: LoadBalancer  # Para expor externamente, pode ser NodePort ou ClusterIP, dependendo do ambiente
