apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-score
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-score
  template:
    metadata:
      labels:
        app: backend-score
    spec:
      containers:
        - name: backend-score
          image: backend-kotlin
          ports:
            - containerPort: 8080
            - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranking-service
  template:
    metadata:
      labels:
        app: ranking-service
    spec:
      containers:
        - name: ranking-service
          image: backend-kotlin
          ports:
            - containerPort: 8081
