apiVersion: v1
kind: Service
metadata:
  name: backend-score-service
spec:
  selector:
    app: backend-score
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ranking-service-service
spec:
  selector:
    app: ranking-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
